version: '3'
services: 
  api:
    build: .
    ports: 
      - '3000:3000'
    volumes: 
      - '.:/app'
      - 'node_modules:/app/node_modules'
    environment:
      DATABASE_URL: postgres://postgres:secret@db:5432/my-calendar
      DATABASE_NAME: my_calendar
      DATABASE_USER: postgres
      DATABASE_PASSWORD: secret
      DATABASE_HOST: db
    command: npm run dev
  db:
    image: postgres:10.5-alpine
    ports:
    - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
  adminer:
    image: adminer
    ports:
      - "9000:8080"
    environment:
      ADMINER_PLUGINS: "dump-json"
volumes:
  dbdata:
  node_modules: